name: 'PR'
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn
          yarn format
          yarn package
      - uses: ./
        id: doc
      - run: echo ${{steps.doc.outputs.doc}}
